---

- name: Include prep
  include_tasks: prep.yaml

- name: Load parameters from {{ fp_parameter_file }}
  include_vars:
    file: "{{ fp_parameter_file }}"

# A kubernetes host and an API key must be set.
# Either environment variables wil have been set by the user
# or AWX 'kubernetes' credentials will have injected them.
# Either way the variables 'k8s_auth_host' and
# 'k8s_auth_api_key' must have been set.
- name: Assert authentication
  assert:
    that:
    - k8s_auth_host|length > 0
    - k8s_auth_api_key|length > 0

- name: Assert kubeconfig file is named
  assert:
    that:
    - fp_kubeconfig_file|length > 0
    - fp_kubeconfig_file!='SetMe'

# Go...

# There is no 'undeploy' fragmentation is a 'Job'
# so there's (normally) nothing to delete.

- name: Deploy
  module_defaults:
    group/k8s:
      host: "{{ k8s_auth_host }}"
      api_key: "{{ k8s_auth_api_key }}"
  block:

  - name: Include deploy
    include_tasks: deploy.yaml
